#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

source docker/_shared.sh

build_images
enable_display_passthrough

# We don't use `docker compose run ...` for tests, because we don't want to have network
# mode be 'host' for tests, and we also want to mount in the 'pkgs' directory wholesale,
# while usually it contains everything _except_ the tests.
docker run -it \
  `# Disable GPU to make the testing more similar to the Github Actions environment` \
  --runtime runc \
  `# For display passthrough, for tests that have visualization options during dev` \
  -e DISPLAY="${DISPLAY}" \
  -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  `# Tests are excluded from the image, so we need to reintroduce them. This` \
  `# saves us from having to rebuild ROS packages for test changes.` \
  -v "$(pwd)/pkgs:/robot/pkgs" \
  ${BUILT_IMAGE_NAME} \
  colcon-test "${@}"
